# Image de base Node.js compatible avec Mac M1 (ARM64)
FROM node:18-alpine

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copie des fichiers de dépendances pour optimiser le cache
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie du reste du code source
COPY . .

ENV VITE_API_BASE_URL=http://backend:3000


# Exposition du port utilisé par Vite (5173 par défaut)
EXPOSE 5173

# Commande pour lancer le serveur de développement Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
